spring:
  profiles:
  active:
    dev

---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-melted-dev

---
spring:
  profiles: test
  application:
    name: microservicecloud-config-melted-test